project ‘ApplozicSwiftDemo.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ApplozicSwiftDemo' do
    pod 'ApplozicSwift', :path => '../ApplozicSwift.podspec'
    #pod 'Applozic', :git => 'https://github.com/StockvivaOP/Applozic-Chat-iOS-Framework.git', :branch => 'feature/SV_Sprint_26'
    pod 'Applozic', :git => 'https://github.com/StockvivaOP/Applozic-Chat-iOS-Framework.git', :branch => 'feature/SVApplozicObjcSDK'
    #pod 'Applozic', :git => 'https://github.com/AppLozic/Applozic-Chat-iOS-Framework.git', :branch => 'reply-api'
    pod 'SwiftLint'
end

target 'ApplozicSwiftDemoTests' do
    pod 'ApplozicSwift', :path => '../ApplozicSwift.podspec'
    #pod 'Applozic', :git => 'https://github.com/StockvivaOP/Applozic-Chat-iOS-Framework.git', :branch => 'feature/SV_Sprint_26'
    pod 'Applozic', :git => 'https://github.com/StockvivaOP/Applozic-Chat-iOS-Framework.git', :branch => 'feature/SVApplozicObjcSDK'
    #pod 'Applozic', :git => 'https://github.com/AppLozic/Applozic-Chat-iOS-Framework.git', :branch => 'reply-api'
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
end
